@startsalt layout-gui
{#
    [Start] |
    "Center Frequency"
    {
        **Settings**
        ^Device^
        "Bandwidth"
    } |
    {+
        {/ <b>Spectrum | Demodulated}
        .
        .
        .
        .
    }
}
@endsalt